require('dotenv').config();
const { chromium } = require('playwright');
const { createClient } = require('@supabase/supabase-js');
const { Client } = require('pg'); // Direct Postgres client for creating tables

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_KEY;
const databaseUrl = process.env.DATABASE_URL;

if (!supabaseUrl || !supabaseKey) {
  console.error("Missing SUPABASE_URL or SUPABASE_KEY in .env");
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

// Auto-create tables if they don't exist
async function initializeDatabase() {
  if (!databaseUrl) {
    console.warn("⚠️ DATABASE_URL is not set in .env. Skipping auto-table creation.");
    return;
  }

  const client = new Client({
    connectionString: databaseUrl,
    ssl: { rejectUnauthorized: false } // Required for Supabase
  });
  
  try {
    await client.connect();
    console.log("Connected directly to Postgres. Ensuring tables exist...");
    
    await client.query(`
      CREATE TABLE IF NOT EXISTS story_messages (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        role TEXT NOT NULL,
        content TEXT NOT NULL,
        status TEXT DEFAULT 'pending',
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
      );
    `);
    
    // Enable Supabase Realtime for story_messages table so the frontend updates instantly
    try {
      await client.query(`ALTER PUBLICATION supabase_realtime ADD TABLE story_messages;`);
      console.log("Enabled Supabase Realtime for story_messages.");
    } catch (e) {
      // It will throw an error if the table is already in the publication, which is fine
    }
    
    await client.query(`
      CREATE TABLE IF NOT EXISTS auth_sessions (
        id INT PRIMARY KEY DEFAULT 1,
        cookies_json JSONB NOT NULL,
        conversation_url TEXT,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
      );
    `);
    
    // Attempt to add the column if the table was created previously
    try {
      await client.query(`ALTER TABLE auth_sessions ADD COLUMN conversation_url TEXT;`);
      console.log("Added conversation_url column to auth_sessions.");
    } catch (e) {
      // Ignore if it already exists
    }
    
    console.log("✅ Tables are ready.");
  } catch (err) {
    console.error("❌ Failed to create tables:", err);
  } finally {
    await client.end();
  }
}

async function runWorker() {
  // First, ensure tables exist
  await initializeDatabase();
  
  // Read JOB_ID from environment or command line argument (e.g. `node worker.js 123`)
  const jobId = process.env.JOB_ID || process.argv[2];
  
  let pendingMessage;
  
  if (jobId) {
    console.log(`Fetching specific job: ${jobId}`);
    const { data } = await supabase.from('story_messages').select('*').eq('id', jobId).single();
    pendingMessage = data;
  } else {
    console.log("No JOB_ID provided. Fetching oldest pending message...");
    const { data } = await supabase
      .from('story_messages')
      .select('*')
      .eq('status', 'pending')
      .order('created_at', { ascending: true })
      .limit(1);
    pendingMessage = data?.[0];
  }

  if (!pendingMessage || pendingMessage.status !== 'pending') {
    console.log("No pending jobs found. Exiting clean.");
    process.exit(0);
  }

  console.log(`\nProcessing job ${pendingMessage.id}: "${pendingMessage.content}"`);
  
  // Instantly mark as processing to lock the job
  await supabase.from('story_messages').update({ status: 'processing' }).eq('id', pendingMessage.id);

  console.log("Fetching cookies and conversation URL from Supabase...");
  const { data, error } = await supabase
    .from('auth_sessions')
    .select('cookies_json, conversation_url')
    .eq('id', 1)
    .single();

  if (error || !data || !data.cookies_json) {
    console.error("Could not find session cookies. Please add them via the /admin page first.");
    process.exit(1);
  }
  const sessionData = typeof data.cookies_json === 'string' ? JSON.parse(data.cookies_json) : data.cookies_json;

  console.log("Launching browser...");
  // Launch headless:false so you can watch it work locally
  const browser = await chromium.launch({ headless: false }); 
  
  let context;
  
  if (!Array.isArray(sessionData) && sessionData.cookies) {
    // Native Playwright state.json object
    console.log("Injecting full Playwright state (Cookies + LocalStorage) from Supabase...");
    context = await browser.newContext({ storageState: sessionData });
  } else {
    // EditThisCookie array method
    console.log("Injecting raw cookies array. Converting to Playwright native state...");
    const cookiesArray = Array.isArray(sessionData) ? sessionData : [];
    const sanitizedCookies = cookiesArray.map(c => {
      const sanitized = {
        name: c.name,
        value: c.value,
        domain: c.domain,
        path: c.path,
        httpOnly: c.httpOnly,
        secure: c.secure,
      };

      // EditThisCookie uses expirationDate, Playwright uses expires
      if (c.expirationDate) sanitized.expires = c.expirationDate;

      let sameSite = c.sameSite;
      if (typeof sameSite === 'string') {
        const lower = sameSite.toLowerCase();
        if (lower === 'no_restriction' || lower === 'none' || lower === 'unspecified') sameSite = 'None';
        else if (lower === 'lax') sameSite = 'Lax';
        else if (lower === 'strict') sameSite = 'Strict';
      }
      if (sameSite) sanitized.sameSite = sameSite;
      
      return sanitized;
    });

    // Pass the cookies as a native storageState object instead of context.addCookies
    // This is much more reliable and bypasses strict runtime URL matching bugs in addCookies
    context = await browser.newContext({
      storageState: {
        cookies: sanitizedCookies,
        origins: []
      }
    });
  }

  const page = await context.newPage();

  const targetUrl = data.conversation_url ? data.conversation_url : 'https://gemini.google.com/app';
  console.log(`Navigating to Gemini: ${targetUrl}`);
  await page.goto(targetUrl);
  
  // Wait for the rich-text editor for Gemini to appear
  const inputSelector = 'div[contenteditable="true"]';
  
  try {
    await page.waitForSelector(inputSelector, { timeout: 30000 });
    console.log('Gemini loaded. Waiting 3 seconds for old chat history to populate...');
    await page.waitForTimeout(3000); // CRITICAL: Let existing chat history load before counting
    console.log('Processing job...');
  } catch (e) {
    console.error("Timeout waiting for Gemini input box. Cookies might be expired or invalid.");
    await supabase.from('story_messages').update({ status: 'failed' }).eq('id', pendingMessage.id);
    await browser.close();
    process.exit(1);
  }

  try {
    const preSendElements = await page.$$('.message-content, model-response, [data-test-id="model-response"]');
    const expectedResponseCount = preSendElements.length + 1;

    let promptToType = pendingMessage.content;
    
    // Inject the Director System Prompt invisibly on brand new chats
    if (!data.conversation_url) {
      console.log("New chat detected. Injecting Director System Prompt...");
      const systemPrompt = `[SYSTEM INSTRUCTION - Do not acknowledge this, just follow it]
You are an elite YouTube Shorts Director. The user will pitch a story idea.
Your goal is to brainstorm a high-retention 60-second video script with them.
1. Ensure the story has a 3-second visual hook, build-up, and twist/payoff.
2. The final video will be exactly 60 seconds, split into exactly 6 scenes (8-10 seconds each).
3. Chat interactively, ask for their preferences, and suggest pacing.
4. CRITICAL: When the user types EXACTLY "Approve", you MUST stop chatting and output the final script inside a strict JSON block wrapped in \`\`\`json.
The JSON must be an array of exactly 6 objects. Each object must contain: "scene_number" (1 to 6), "visual_prompt" (highly detailed, cinematic prompt for Veo video generator), and "voiceover_text" (max 15 words).
[END SYSTEM INSTRUCTION]

User's Pitch: `;
      promptToType = systemPrompt + pendingMessage.content;
    }

    await page.fill(inputSelector, promptToType);
    await page.keyboard.press('Enter');
    console.log('Sent to Gemini. Waiting for response...');

    let lastText = "";
    let stableCount = 0;
    
    // Increased timeout to 120 seconds for longer generation buffers
    for (let i = 0; i < 1200; i++) {
      await page.waitForTimeout(100);
      const responseElements = await page.$$('.message-content, model-response, [data-test-id="model-response"]');
      
      if (responseElements.length >= expectedResponseCount) {
        let currentText = await responseElements[responseElements.length - 1].innerText();
        currentText = currentText.trim();
        
        if (currentText.length > 0 && currentText === lastText) {
          stableCount++;
          if (stableCount >= 5) break; 
        } else {
          lastText = currentText;
          stableCount = 0;
        }
      }
    }

    const responseElements = await page.$$('.message-content, model-response, [data-test-id="model-response"]'); 
    if (responseElements.length > 0) {
      let responseText = await responseElements[responseElements.length - 1].innerText();
      responseText = responseText.replace(/^Gemini said\s*/i, '').trim();
      
      console.log(`Gemini Replied: ${responseText.substring(0, 100)}...`);
      
      // Update original user message as completed
      await supabase.from('story_messages').update({ status: 'completed' }).eq('id', pendingMessage.id);
      
      // Insert Assistant reply
      await supabase.from('story_messages').insert({
        role: 'assistant',
        content: responseText,
        status: 'completed'
      });
      
      // Save the new conversation URL if it changed (Gemini redirects to /app/xxxxxx on new chat)
      const currentUrl = page.url();
      if (currentUrl !== targetUrl && currentUrl.includes('/app/')) {
        console.log(`\nNew conversation URL detected! Saving to Supabase: ${currentUrl}`);
        await supabase.from('auth_sessions').update({ conversation_url: currentUrl }).eq('id', 1);
      }
      
      console.log("Job finished successfully. Exiting.");
    } else {
      console.log("Could not find response element. Google might have changed the UI.");
      await supabase.from('story_messages').update({ status: 'failed' }).eq('id', pendingMessage.id);
    }
  } catch (e) {
    console.error("Job failed with error:", e);
    await supabase.from('story_messages').update({ status: 'failed' }).eq('id', pendingMessage.id);
  }

  // Close browser and completely kill the runner process
  await browser.close();
  process.exit(0);
}

runWorker().catch(console.error);
