require('dotenv').config();
const { chromium } = require('playwright');
const { createClient } = require('@supabase/supabase-js');
const { Client } = require('pg'); // Direct Postgres client for creating tables

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_KEY;
const databaseUrl = process.env.DATABASE_URL;

if (!supabaseUrl || !supabaseKey) {
  console.error("Missing SUPABASE_URL or SUPABASE_KEY in .env");
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

// Auto-create tables if they don't exist
async function initializeDatabase() {
  if (!databaseUrl) {
    console.warn("⚠️ DATABASE_URL is not set in .env. Skipping auto-table creation.");
    return;
  }

  const client = new Client({
    connectionString: databaseUrl,
    ssl: { rejectUnauthorized: false } // Required for Supabase
  });
  
  try {
    await client.connect();
    console.log("Connected directly to Postgres. Ensuring tables exist...");
    
    await client.query(`
      CREATE TABLE IF NOT EXISTS story_messages (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        role TEXT NOT NULL,
        content TEXT NOT NULL,
        status TEXT DEFAULT 'pending',
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
      );
    `);
    
    await client.query(`
      CREATE TABLE IF NOT EXISTS auth_sessions (
        id INT PRIMARY KEY DEFAULT 1,
        cookies_json JSONB NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
      );
    `);
    
    console.log("✅ Tables are ready.");
  } catch (err) {
    console.error("❌ Failed to create tables:", err);
  } finally {
    await client.end();
  }
}

async function runWorker() {
  // First, ensure tables exist
  await initializeDatabase();

  console.log("Fetching cookies from Supabase...");
  // 1. Fetch cookies from Supabase
  const { data, error } = await supabase
    .from('auth_sessions')
    .select('cookies_json')
    .eq('id', 1)
    .single();

  if (error || !data || !data.cookies_json) {
    console.error("Could not find session cookies in Supabase. Please add them via the /admin page first.");
    process.exit(1);
  }

  const cookies = typeof data.cookies_json === 'string' ? JSON.parse(data.cookies_json) : data.cookies_json;

  console.log("Launching browser...");
  // Launch headless:false so you can watch it work locally
  const browser = await chromium.launch({ headless: false }); 
  const context = await browser.newContext();
  
  // Load the cookies into the browser context
  await context.addCookies(cookies);

  const page = await context.newPage();

  console.log("Navigating to Gemini...");
  await page.goto('https://gemini.google.com/app');
  
  // Wait for the rich-text editor for Gemini to appear
  const inputSelector = 'div[contenteditable="true"]';
  
  try {
    await page.waitForSelector(inputSelector, { timeout: 30000 });
    console.log('Gemini loaded successfully! Worker is now polling Supabase...');
  } catch (e) {
    console.error("Timeout waiting for Gemini input box. Cookies might be expired or invalid.");
    await browser.close();
    process.exit(1);
  }
  
  while (true) {
    // Fetch oldest pending message
    const { data: pendingMessages } = await supabase
      .from('story_messages')
      .select('*')
      .eq('status', 'pending')
      .order('created_at', { ascending: true })
      .limit(1);

    const pendingMessage = pendingMessages?.[0];

    if (pendingMessage) {
      console.log(`\nNew message found: "${pendingMessage.content}"`);
      
      // Update status to 'processing' so we don't pick it up again
      await supabase.from('story_messages').update({ status: 'processing' }).eq('id', pendingMessage.id);

      // Type and Send
      await page.fill(inputSelector, pendingMessage.content);
      await page.keyboard.press('Enter');
      console.log('Sent to Gemini. Waiting for response...');

      // Wait for generation to finish (waiting for network idle is a simple heuristic)
      await page.waitForLoadState('networkidle');
      // Adding a buffer to ensure DOM text rendering is complete
      await page.waitForTimeout(5000); 

      // Extract the last response. 
      const responseElements = await page.$$('.message-content, model-response, [data-test-id="model-response"]'); 
      
      if (responseElements.length > 0) {
        const lastResponse = responseElements[responseElements.length - 1];
        const responseText = await lastResponse.innerText();
        
        console.log(`Gemini Replied: ${responseText.substring(0, 100)}...`);
        
        // Mark user message as completed
        await supabase.from('story_messages').update({ status: 'completed' }).eq('id', pendingMessage.id);
        
        // Insert the Assistant's reply
        await supabase.from('story_messages').insert({
          role: 'assistant',
          content: responseText,
          status: 'completed'
        });
        
        console.log("Supabase updated. Waiting for next message...");
      } else {
        console.log("Could not find response element. Google might have changed the UI.");
        await supabase.from('story_messages').update({ status: 'failed' }).eq('id', pendingMessage.id);
      }
    }
    
    // Poll every 3 seconds
    await page.waitForTimeout(3000); 
  }
}

runWorker().catch(console.error);
