require('dotenv').config();
const { chromium } = require('playwright');
const { createClient } = require('@supabase/supabase-js');
const { Client } = require('pg'); // Direct Postgres client for creating tables
const express = require('express');
const cors = require('cors');

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_KEY;
const databaseUrl = process.env.DATABASE_URL;

if (!supabaseUrl || !supabaseKey) {
  console.error("Missing SUPABASE_URL or SUPABASE_KEY in .env");
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

// Auto-create tables if they don't exist
async function initializeDatabase() {
  if (!databaseUrl) {
    console.warn("⚠️ DATABASE_URL is not set in .env. Skipping auto-table creation.");
    return;
  }

  const client = new Client({
    connectionString: databaseUrl,
    ssl: { rejectUnauthorized: false } // Required for Supabase
  });
  
  try {
    await client.connect();
    console.log("Connected directly to Postgres. Ensuring tables exist...");
    
    await client.query(`
      CREATE TABLE IF NOT EXISTS story_messages (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        role TEXT NOT NULL,
        content TEXT NOT NULL,
        status TEXT DEFAULT 'pending',
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
      );
    `);
    
    // Enable Supabase Realtime for story_messages table so the frontend updates instantly
    try {
      await client.query(`ALTER PUBLICATION supabase_realtime ADD TABLE story_messages;`);
      console.log("Enabled Supabase Realtime for story_messages.");
    } catch (e) {
      // It will throw an error if the table is already in the publication, which is fine
    }
    
    await client.query(`
      CREATE TABLE IF NOT EXISTS auth_sessions (
        id INT PRIMARY KEY DEFAULT 1,
        cookies_json JSONB NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
      );
    `);
    
    console.log("✅ Tables are ready.");
  } catch (err) {
    console.error("❌ Failed to create tables:", err);
  } finally {
    await client.end();
  }
}

async function runWorker() {
  // First, ensure tables exist
  await initializeDatabase();

  console.log("Fetching cookies from Supabase...");
  const { data, error } = await supabase
    .from('auth_sessions')
    .select('cookies_json')
    .eq('id', 1)
    .single();

  if (error || !data || !data.cookies_json) {
    console.error("Could not find session cookies. Please add them via the /admin page first.");
    process.exit(1);
  }
  const sessionData = typeof data.cookies_json === 'string' ? JSON.parse(data.cookies_json) : data.cookies_json;

  console.log("Launching browser...");
  // Launch headless:false so you can watch it work locally
  const browser = await chromium.launch({ headless: false }); 
  
  let context;
  
  if (!Array.isArray(sessionData) && sessionData.cookies) {
    // Native Playwright state.json object
    console.log("Injecting full Playwright state (Cookies + LocalStorage) from Supabase...");
    context = await browser.newContext({ storageState: sessionData });
  } else {
    // EditThisCookie array method
    console.log("Injecting raw cookies array. Converting to Playwright native state...");
    const cookiesArray = Array.isArray(sessionData) ? sessionData : [];
    const sanitizedCookies = cookiesArray.map(c => {
      const sanitized = {
        name: c.name,
        value: c.value,
        domain: c.domain,
        path: c.path,
        httpOnly: c.httpOnly,
        secure: c.secure,
      };

      // EditThisCookie uses expirationDate, Playwright uses expires
      if (c.expirationDate) sanitized.expires = c.expirationDate;

      let sameSite = c.sameSite;
      if (typeof sameSite === 'string') {
        const lower = sameSite.toLowerCase();
        if (lower === 'no_restriction' || lower === 'none' || lower === 'unspecified') sameSite = 'None';
        else if (lower === 'lax') sameSite = 'Lax';
        else if (lower === 'strict') sameSite = 'Strict';
      }
      if (sameSite) sanitized.sameSite = sameSite;
      
      return sanitized;
    });

    // Pass the cookies as a native storageState object instead of context.addCookies
    // This is much more reliable and bypasses strict runtime URL matching bugs in addCookies
    context = await browser.newContext({
      storageState: {
        cookies: sanitizedCookies,
        origins: []
      }
    });
  }

  const page = await context.newPage();

  console.log("Navigating to Gemini...");
  await page.goto('https://gemini.google.com/app');
  
  // Wait for the rich-text editor for Gemini to appear
  const inputSelector = 'div[contenteditable="true"]';
  
  try {
    await page.waitForSelector(inputSelector, { timeout: 30000 });
    console.log('Gemini loaded successfully! Worker is now polling Supabase...');
  } catch (e) {
    console.error("Timeout waiting for Gemini input box. Cookies might be expired or invalid.");
    await browser.close();
    process.exit(1);
  }
  
  // Start Express API server
  const app = express();
  app.use(cors());
  app.use(express.json());

  app.post('/api/chat', async (req, res) => {
    const { message } = req.body;
    if (!message) return res.status(400).json({ error: "Message is required" });

    console.log(`\nNew API message received: "${message}"`);
    
    // Asynchronously save user message to Supabase
    supabase.from('story_messages').insert({
      role: 'user',
      content: message,
      status: 'completed'
    }).then();

    try {
      const preSendElements = await page.$$('.message-content, model-response, [data-test-id="model-response"]');
      const expectedResponseCount = preSendElements.length + 1;

      await page.fill(inputSelector, message);
      await page.keyboard.press('Enter');
      console.log('Sent to Gemini. Waiting for response...');

      let lastText = "";
      let stableCount = 0;
      
      for (let i = 0; i < 600; i++) {
        await page.waitForTimeout(100);
        const responseElements = await page.$$('.message-content, model-response, [data-test-id="model-response"]');
        
        if (responseElements.length >= expectedResponseCount) {
          let currentText = await responseElements[responseElements.length - 1].innerText();
          currentText = currentText.trim();
          
          if (currentText.length > 0 && currentText === lastText) {
            stableCount++;
            if (stableCount >= 5) break; 
          } else {
            lastText = currentText;
            stableCount = 0;
          }
        }
      }

      const responseElements = await page.$$('.message-content, model-response, [data-test-id="model-response"]'); 
      if (responseElements.length > 0) {
        let responseText = await responseElements[responseElements.length - 1].innerText();
        responseText = responseText.replace(/^Gemini said\s*/i, '').trim();
        
        console.log(`Gemini Replied: ${responseText.substring(0, 100)}...`);
        
        // Asynchronously save assistant message to Supabase
        supabase.from('story_messages').insert({
          role: 'assistant',
          content: responseText,
          status: 'completed'
        }).then();
        
        // Return instantly to frontend
        res.json({ reply: responseText });
      } else {
        res.status(500).json({ error: "Could not find response element. Google might have changed the UI." });
      }
    } catch (e) {
      console.error(e);
      res.status(500).json({ error: e.message });
    }
  });

  const PORT = 4000;
  app.listen(PORT, () => {
    console.log(`\n🚀 Worker API running on http://localhost:${PORT}`);
    console.log('Frontend can now bypass Supabase polling and call this API directly!');
  });
}

runWorker().catch(console.error);
